### ISSUE TITLE
Import Error while Installing

### ISSUE THREAD

**Issue by rmassidda** [agmmnn/synonym-cli#2]
Hey!

Firstly, thanks for the useful script. :)

I tried to install the package but I found two minor errors that resulted in failure.
Firstly, importing the version number from `__main__.py` causes the import of the external libraries.
Thus, the package installation fails if the external libraries are not already installed (as in my case!).
Secondly, the README file has a different extension than the one reported in `setup.py`.

I'm preparing a pull request fixing this, hoping it might help!

**Comment by agmmnn** [comment]
I was using this way in my other packages as well, I didn't know it was causing an error. Thank you for the feedback.

https://github.com/agmmnn/synonym-cli/releases/tag/v0.0.5
