### ISSUE TITLE
Thesaurus.com parsing fails due to potential changes on the site

### ISSUE THREAD

**Issue by ghostofpokemon** [agmmnn/synonym-cli#4]
Hello,

I've noticed that `synonym-cli` is currently unable to parse data from Thesaurus.com, likely due to changes on the site. This results in a failure when trying to get synonyms or antonyms for any word. The error message I'm receiving is:

```shell
Expecting value: line 1 column 1 (char 0)
```
I've already developed a fix for this issue by utilizing BeautifulSoup to parse the necessary JSON data from the site. This solution seems to work well and I will soon open a pull request for your review. This way, users can continue to enjoy this useful tool.

**Comment by agmmnn** [comment]
https://github.com/agmmnn/syn/releases/tag/v0.3.0
